name: ApexRoulette
attributes:
  ORGANIZATIONNAME: Daiki Umehara
options:
  bundleIdPrefix: com.gmail.daikiumehara3
  deploymentTarget:
    iOS: 15.0
  developmentLanguage: ja
  DEVELOPMENT_TEAM: 28624T34F8
packages:
  Rswift:
    url: https://github.com/mac-cain13/R.swift.Library
    from: 5.4.0
targets:
  ApexRoulette:
    type: application
    platform: iOS
    sources: [ApexRoulette]
    settings:
      base:
        CURRENT_PROJECT_VERSION: 1.0
        PRODUCT_NAME: ApexRoulette
      configs:
        debug:
          CUSTOM_BUILD_SETTING: my_debug_value
        release:
          CUSTOM_BUILD_SETTING: my_release_value
    dependencies:
      - package: Rswift
    info:
      path: ApexRoulette/Info.plist
      properties:
        UISupportedInterfaceOrientations: [UIInterfaceOrientationPortrait]
        UILaunchStoryboardName: LaunchScreen
        AppUsesNon-ExemptEncryption: NO
        TargetedDeviceFamilies: [iPhone]
        SupportedDestinations: [iPhone]
        Appearance: Light
    preBuildScripts:
      - name: Run R.swift
        shell: /bin/sh
        basedOnDependencyAnalysis: false
        outputFiles:
        - $(SRCROOT)/Rswift/R.generated.swift
        script: |
          if [ $(uname -m) = "arm64" ]; then
            export PATH="/opt/homebrew/bin:/opt/homebrew/sbin:${PATH+:$PATH}";
          fi
          mint run mac-cain13/R.swift@v6.1.0 rswift generate "${SRCROOT}/ApexRoulette/SupportFiles/Rswift/R.generated.swift"

settingGroups:
  appBaseSettings:
    DEVELOPMENT_TEAM: 28624T34F8
